general {
    lock_cmd = pidof hyprlock || hyprlock       # comando para bloquear la pantalla
    before_sleep_cmd = loginctl lock-session    # bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # encender la pantalla al despertar
}

# Bloquear la pantalla tras 60 segundos de inactividad
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Apagar monitores 4 segundos después del bloqueo (64s total)
listener {
    timeout = 64
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on          # encender al detectar actividad
}

# Suspender tras 30 minutos de inactividad
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
